export interface Giocatore {
  id: number,
  nome: string,
  cognome: string,
  dataNascita: string,
  piede: string,
  altezza: string,
  nazionalita: string,
  ruolo: string,
  ruoloMantra: string,
  squadra: string,
  overall: number,
  rarita: string,
  skill: string,
  fantaMedia: number,
  mediaVoto: number,
  espanso: boolean,
  card: string,
  partiteGiocate: number,
  reti: number,
  assist: number,
  cleanSheet: number,
  goalSubiti: number,
  ammonizioni: number,
  espulsioni: number,
  rigoriTirati: number,
  rigoriSegnati: number,
  rigoriRicevuti: number,
  rigoriParati: number,
  quotazione: number

}
